#!/bin/bash

set -eu

CLUSTER_NAME="istio-testing"
ISTIO_VERSION="1.6.2"

# Create cluster
kind create cluster --name "$CLUSTER_NAME" --config=cluster.yaml

# Create Ingress
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

# Download istio
[[ -d "istio-$ISTIO_VERSION" ]] || curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION sh -

# Install istio
pushd "istio-$ISTIO_VERSION"
export PATH="$PWD/bin:$PATH"


# Install istio
istioctl install --set profile=demo
kubectl label namespace default istio-injection=enabled

# Deploy Sample Application
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

# Setup app ingress
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

popd


